### ISSUE TITLE
Unable to load template

### ISSUE THREAD

**Issue by sevilyilmaz** [erinspice/confluence-jsdoc-template#3]
I've got an error:

throw new Error('Unable to load template: ' + e.message || e);
       ^
Unable to load template: Cannot find module 'templates/confluence-jsdoc-template/publish'
...

**Comment by jurgob** [comment]
HI hade the same problem and I've used the same solution.
now, on publish.js my 8th line is:
wikiHelper = require('./templateHelper'),

**Comment by erinspice** [comment]
Ok, I trust you. I'll commit it.
